secret = "7iyWxYJExzq8ThKteTQSenVwcm95LnNhZmVzdXJmLnRlY2g"
bind-to = "0.0.0.0:3128"
concurrency = 8192
prefer-ip = "prefer-ipv6"

[network.timeout]
tcp = "5s"
http = "10s"
idle = "1m"

[stats.prometheus]
enabled = true
bind-to = "0.0.0.0:8080"
http-path = "/metrics"